Chearn/Chearn/Models/Cours.cs
namespace Chearn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Courses")]
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            Lessons = new HashSet<Lesson>();
        }
        public int ID { get; set; }

        public int? InstructorID { get; set; }

        [Required]
        [StringLength(256)]
        public string Name { get; set; }

        public string Description { get; set; }

        public string Tag { get; set; }

        public virtual Instructor Instructor { get; set; }

        public byte[] Picture { get; set; }

        public bool Valid { get; set; }

        public bool Comfirmed { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lessons { get; set; }

        
    }
}

Chearn/Chearn/Models/Lesson.cs
namespace Chearn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            Edges = new HashSet<Edge>();
            Edges1 = new HashSet<Edge>();
            Questions = new HashSet<Question>();
            StudentLessons = new HashSet<StudentLesson>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(512)]
        public string Title { get; set; }
        [Required]
        [StringLength(8000)]
        [DataType(DataType.MultilineText)]
        public string MaterialA { get; set; }

        [Required]
        [StringLength(8000)]
        [DataType(DataType.MultilineText)]
        public string MaterialB { get; set; }

        
        [StringLength(3000)]
        public string ImageLink { get; set; }

        
        [StringLength(512)]
        public string VideoLink { get; set; }
        public int? CourseID { get; set; }
        //public int XPosition { get; set; }
        //public int YPosition { get; set; }
        public virtual Cours Cours { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edge> Edges { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edge> Edges1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLesson> StudentLessons { get; set; }
    }
}

Chearn/Chearn/Models/ViewModels/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chearn.Models.ViewModels
{
    public class LessonViewModel
    {
        public Lesson lesson { get; set; }
        public List<Question> questions { get; set; }

    }
}

Chearn/Chearn/Controllers/CoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Chearn.Controllers;
using Chearn.Models;
using Chearn.Models.ViewModels;
using Microsoft.AspNet.Identity;


namespace Chearn.Controllers
{

    public class CoursController : Controller
    {
        private ChearnContext db = new ChearnContext();
        [Authorize(Roles = "Instructor, Admin")]
        // GET: Cours
        public ActionResult Index()
        {
            var aspID = User.Identity.GetUserId();

            var cuser = db.CUsers.Single(i => i.AspID == aspID);

            List<Cours> courses = new List<Cours>();
            var course = db.CourseInstructors.Where(x => x.InstructorID == cuser.ID).ToList();
            foreach(var item in course)
            {

                var temp = db.Courses.Find(item.CourseID);
                courses.Add(temp);
            }
            return View(courses);
        }

        [Authorize(Roles = "Instructor")]
        // GET: Cours/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,InstructorID,Name, Tag")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                cours.InstructorID = InstructorController.GetCurrentInstructor(User.Identity.GetUserId()).CUserID;
                HttpPostedFileBase image = Request.Files["ImageData"];
                if(image != null)
                {
                    cours.Picture = ConvertToBytes(image);
                }
                cours.Valid = false;
                cours.Comfirmed = false;
                db.Courses.Add(cours);
                db.SaveChanges();
                db.CourseInstructors.Add(new CourseInstructor { InstructorID = cours.InstructorID, CourseID = cours.ID });
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cours);
        }

        public ActionResult Remove(int id)
        {
            var removed = db.Courses.Find(id);
            removed.Comfirmed = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public byte[] ConvertToBytes(HttpPostedFileBase image)
        {
            byte[] imageBytes = null;
            System.IO.BinaryReader reader = new System.IO.BinaryReader(image.InputStream);
            imageBytes = reader.ReadBytes((int)image.ContentLength);
            return imageBytes;
        }

        [Authorize(Roles = "Instructor, Admin")]
        // GET: Cours/Edit/5
        public ActionResult Edit(int? id)
        {
            ActionResult errorResult;
            var isAutheticated = this.IsAutheticated(id, out errorResult);
            if (!isAutheticated)
                return errorResult;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            ViewBag.InstructorID = new SelectList(db.Instructors, "ID", "ID", cours.InstructorID);
            return View(cours);
        }
        public ActionResult StudentInfo(int? id) 
        {
            ViewBag.CourseID = id.Value;

            return View();
        }


        [Authorize(Roles = "Instructor, Admin")]
        // POST: Cours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,InstructorID,Name, Valid")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.InstructorID = new SelectList(db.Instructors, "ID", "ID", cours.InstructorID);
            return View(cours);
        }

        public JsonResult SetCourseValidationState(int courseID, bool valid)
        {
            var course = db.Courses.Find(courseID);
            course.Valid = valid;
            db.SaveChanges();
            return Json("Validation changed", JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public async Task<ActionResult> Info(int id) 
        {
            ViewBag.CourseID = id;
            //TODO: implement variable rolling average
            const int RollingAverageDays = 1;
            const int ActiveTimeLimit = 30;
            ActionResult result;
            //Course authenticaion 
            if (!IsAutheticated(id, out result))
                return result;

            var course = await db.Courses.FindAsync(id);
            var model = new AggregateStatsViewModel();
            var courseLessons = db.Lessons.Where(l => l.CourseID == id);
            var courseQuestions = db.Questions.ToList().Where(q => courseLessons.Where(c => c.ID == q.LessonID.Value).Any()).ToList();
            var courseReviews = db.Reviews.ToList().Where(r => courseQuestions.Where(q => q.ID == r.QuestionID).Any()).ToList();

            model.ID = course.ID;
            model.CourseName = course.Name;
            model.ReviewDays = RollingAverageDays;
            var enrollmentList = await db.Enrollments.Where(e => e.CourseID.Value == id).ToListAsync();
            model.TotalStudents = enrollmentList.Select(e => e.StudentID).Count();
            //active student is defined as a student whose last review was less than (ActiveTimeLimit) days 
            var test = (await ReviewController.GetLatestReviews(id, ActiveTimeLimit)).ToList();
            model.ActiveStudents = model.TotalStudents;//(await ReviewController.GetLatestReviews(id, ActiveTimeLimit)).ToList().GroupBy(r => r.UserID).Count();

            model.CorrectRate = courseReviews.Where(r => r.IsCorrect).Count() / (double)courseReviews.Count();
            model.ChallengeQuestion = new List<Question>();
            foreach(var question in courseQuestions)
            {
                var totalCount = courseReviews.Where(r => r.QuestionID == question.ID).Count();
                var correctCount = courseReviews.Where(r => (r.IsCorrect && r.QuestionID == question.ID)).Count();
                if (totalCount > 0 && ( correctCount / (double)totalCount ) < model.CorrectRate)
                {
                    model.ChallengeQuestion.Add(question);
                }
            }
            List<double> dailyAverages = new List<double>(RollingAverageDays);
            for(int i = 0; i < RollingAverageDays; i++)
            {
                double val = courseReviews.Where(r => r.TimeStamp < DateTime.Now.AddDays(-i) && r.IsCorrect).Count() 
                    / (double)courseReviews.Where(r => r.TimeStamp < DateTime.Now.AddDays(-i)).Count();
                dailyAverages.Add(val);
            }
            model.SMAReviewsPerDay = (dailyAverages.Sum()/dailyAverages.Count());
            


            
            model.ReviewDays = 10;
            return View(model);
        }

        [Authorize(Roles = "Instructor, Admin")]
        // GET: Cours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        [Authorize(Roles = "Instructor, Admin")]
        // POST: Cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) { 
            ActionResult result;
            var isAuthenticated = this.IsAutheticated(id, out result);
            if (!isAuthenticated)
                return result;

            var course = db.Courses.Find(id);
            var lessons = course.Lessons;
            db.Lessons.RemoveRange(lessons);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public bool IsAutheticated(int? id, out ActionResult errorResult)
        {
            errorResult = null;
            //checks whether ID was passed in
            if (id == null)
            {
                errorResult = new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id.Value);
            //checks whether course exists
            if (course == null)
            {
                errorResult = HttpNotFound();
            }
            //checks whether anyone is signed in
            if (!User.Identity.IsAuthenticated)
            {
                errorResult = new HttpStatusCodeResult(HttpStatusCode.Forbidden, "The user is not currently signed in.");
            }
            //checks whether current is an instructor
            var userID = User.Identity.GetUserId();
            if (!InstructorController.UserIsInstructor(userID))
            {
                errorResult = new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Only instructors may access this page.");
            }

            var instructor = db.Instructors.Where(i =>
                i.CUserID == db.CUsers.Where(c =>

Chearn/Chearn/Views/Cours/CourseNode.cshtml
@model Chearn.Models.Cours
@{
    ViewBag.Title = "StudentCourse";
}
<data id="CourseID" value="@ViewBag.CourseID"></data>
<h2>Course Home</h2>
<div class="text-danger" id="warningMessage"></div>

<div class="row">
    <div style="width:18em">
        <div id="resultRow" style="max-height:80em;hidden; overflow-y:scroll;">
            <input class="form-control" id="lessonSearchbar" type="search" />
        </div>
    </div>
    

</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.14.0/cytoscape.min.js")
@Scripts.Render("https://cdn.jsdelivr.net/npm/cytoscape-edgehandles@3.6.0/cytoscape-edgehandles.min.js")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js")
@Scripts.Render("~/Scripts/PageLogic/NodeGraph.js")

Chearn/Chearn/Views/Cours/CourseShare.cshtml
@model List<Chearn.Models.ViewModels.CourseSharingModel>

@{ 
    ViewBag.Title = "CourseShare";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Share Your Course!</h2>


<div class="card-deck">
    @foreach (var Teacher in Model)
    {
        <div class="card course" style = "max-width:20em">
            <div class="card-body">
                @using (Html.BeginForm(Teacher))
                {
                    <div class="form-group">
                        <h5 class="card-title">@Teacher.FirstName @Teacher.LastName</h5>
                        <input type="submit" name="add" value="Add" />
                        <input type="submit" name="remove" value="Remove" />
                    </div>
                }
                </div>
        </div>
    }
</div>

Chearn/Chearn/Views/Cours/Create.cshtml
@model Chearn.Models.Cours

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Cours", FormMethod.Post, new { enctype = "multipart/form-data" } ))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-10">
            <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to My Courses", "Index")
</div>

Chearn/Chearn/Views/Cours/Delete.cshtml
@model Chearn.Models.Cours

@{
    ViewBag.Title = "Delete Course";
}
    
    <div class="row">
        <h2 class="speech-bubble"><div style="">Don't delete me...</div></h2>
        <img src="~/Content/img/SadFace.svg" height="120" width="120" />
    </div>
<h3>Are you sure you want to kill <b>@Model.Name</b> </h3>
<div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" value="Delete" class="cn-icon cn-continue"  >
               Yes <img src="~/Content/icons/check.svg" />    
            </button> |
            <button class="cn-icon cn-stop">
                <a style="text-decoration:none" href="@Url.Action("Index", "Cours")"> Go Back <img src="~/Content/icons/x.svg" /></a>
            </button>
        </div>
    }
</div>

Chearn/Chearn/Views/Cours/Details.cshtml
@model Chearn.Models.Cours

@{
    ViewBag.Title = "Details";
}

<h2> Course Details </h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        
       

        <dt>
            @Html.DisplayFor(model => model.Name)
        </dt>


        <dd>
           Details Related to Course will be Posted Here
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>



<h5>
    <button class='cn-icon'>
        <a href="/Enrollments/Create/?courseID=@Model.ID">Enroll in the Course</a>
    </button>
</h5>



<hr>
<p>
   
    @Html.ActionLink("View All Courses", "Index","CoursesAvailable")
</p>

Chearn/Chearn/Views/Cours/Edit.cshtml
@model Chearn.Models.Cours

@{
    ViewBag.Title = "Edit Course";
}
<data id="CourseID" value="@Model.ID"></data>

<h2>Edit Course</h2>
<hr />

@if (Model.Lessons.Count != 0 || Model.Valid != true || Model.Comfirmed != true)
{
    <h5>Submit course for review <input type="checkbox" id="ValidCheckbox" value="@Model.Valid"/></h5>
}

<div class="row">
    <div style="width:18em">
        <div id="resultRow" style="max-height:80em;hidden; overflow-y:scroll;">
            <input class="form-control" id="lessonSearchbar" type="search" />
        </div>
    </div>
    <div>
        <h5>Add Lesson</h5>
        <button class="cn-icon" style="background-color:var(--accent-bg-color)">
            <a href="@Url.Action("Create", "Lessons", new { id = Model.ID})">Add New Lesson<img src="~/Content/icons/plus.svg" width="32" height="32"></a>
        </button>
    </div>
    <div>
        <h5>Bulk Edit</h5>
        <button class="cn-icon" style="background-color:var(--accent-bg-color)">
            <a href="@Url.Action("Index", "Questions", new { id = Model.ID})">Bulk Edit<img src="~/Content/icons/plus.svg" width="32" height="32"></a>
        </button>
    </div>
    <div>
        <h5>Course Graphing</h5>
        <button class="cn-icon" style="background-color:var(--accent-bg-color)">
            <a href="@Url.Action("NodeGraph", "Cours", new { id = Model.ID})"> Create Course Roadmap <img src="~/Content/icons/plus.svg" width="32" height="32"></a>
        </button>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js")
@Scripts.Render("~/Scripts/PageLogic/EditCourse.js") 
@Scripts.Render("/Scripts/PageLogic/CourseEdit.js")

Chearn/Chearn/Views/Cours/Index.cshtml
@model IEnumerable<Chearn.Models.Cours>

@{
    ViewBag.Title = "Manage Courses";
}

<h2>Manage Courses</h2>

<button class="cn-icon">
    <h5>
        @Html.ActionLink("Add a new Course", "Create")
    </h5>
</button>

<div class="card-deck">
    @foreach (var course in Model)
    {
        <div class="card course" style="max-width:20em">
            <div class="card-body">
                <h5 class="card-title">@course.Name</h5>
                <hr />
                <button class="cn-icon"><a href="@Url.Action("Info", "Cours", new { id = course.ID })"><img src="~/Content/icons/eye.svg" width="24" height="24" alt="Delete" title="Info" /></a></button>
                <button class="cn-icon"><a href="@Url.Action("Edit", "Cours", new { id = @course.ID })"><img src="~/Content/icons/pencil.svg" alt="Edit" width="24" height="24" title="Edit" /></a></button>
                <button class="cn-icon"><a href="@Url.Action("Delete", "Cours", new { id = @course.ID })"><img src="~/Content/icons/trash.svg" width="24" height="24" alt="Delete" title="Delete" /></a></button>
                <button class="cn-icon"><a href="@Url.Action("CourseShare", "Cours", new { id = course.ID })"><img src="~/Content/icons/plus.svg" width="24" height="24" alt="Delete" title="CourseShare" /></a></button>
                <button class="cn-icon"><a href="@Url.Action("Remove", "Cours", new { id = course.ID })"><img src="~/Content/icons/minus.svg" width="24" height="24" title="Remove" /></a></button>
            </div>
        </div>
    }
</div>

Chearn/Chearn/Views/Cours/Info.cshtml
@model Chearn.Models.ViewModels.AggregateStatsViewModel

@{
    ViewBag.Title = "Course Statistics";
}
    <div class="card">
        <h2>@Model.CourseName Statistics </h2>
        <hr />
        <a href="/Cours/StudentInfo/@ViewBag.CourseID">Search For Individual Student's Performance</a>
        <hr />
        <div class="card-group">
            <div class="card">
                <div class="card-title" style="background-color:var(--accent-bg-color)">
                    <br />
                    Active Students
                </div>
                <div class="card-body" style="font-size:24px">
                    @Model.ActiveStudents
                </div>
            </div>
            <div class="card">
                <div class="card-title" style="background-color:var(--accent-bg-color)">
                    <br />
                    Total Students
                </div>
                <div class="card-body" style="font-size:24px">
                    @Model.TotalStudents
                </div>
            </div>
            <div class="card">
                <div class="card-title" style="background-color:var(--accent-bg-color)">
                    <br />
                    Correct Rate
                </div>
                <div class="card-body" style="font-size:24px">
                    @Model.CorrectRate.ToString().Substring(0, Model.CorrectRate.ToString().Count() < 4 ? Model.CorrectRate.ToString().Count() : 4)
                </div>
            </div>
            <div class="card">
                <div class="card-title" style="background-color:var(--accent-bg-color)">
                    <br />
                    SMA Average Reviews (Last @Model.ReviewDays days)
                </div>
                <div class="card-body" style="font-size:24px">
                    @Model.SMAReviewsPerDay.ToString().Substring(0, Model.SMAReviewsPerDay.ToString().Count() < 4 ? Model.SMAReviewsPerDay.ToString().Count() : 4)
                </div>
            </div>
        </div>
        <div class="card">
            Challenge Questions:
            <div>
                @foreach (var question in Model.ChallengeQuestion)
                {
                    <div class="card">
                        <div class="card-title card-header" style="background-color:var(--accent-bg-color)">
                            @question.Lesson.Title
                        </div>
                        <div class="card-body" style="background-color:var(--primary-highlight-color)">
                            @question.Text
                            <br />
                            Answer:<div style="background-color:var(--primary-bg-success);width:4em">@question.Answer</div>
                        </div>
                    </div>
                }
            </div>
        </div>
</div>

Chearn/Chearn/Views/Cours/Lessons.cshtml
@model Chearn.Models.Lesson

@{
    ViewBag.Title = "Lessons";
}
<data id="CourseID" value="@ViewBag.CourseID"></data>
<h2>Enter Lessons in the course</h2>

@Scripts.Render("~/bundles/jquery")

Chearn/Chearn/Views/Cours/NodeGraph.cshtml
@model Chearn.Models.Cours

@{
    ViewBag.Title = "Node Graph";
}

<data id="CourseID" value="@ViewBag.CourseID"></data>
<h2>Lesson Graphing</h2>
<div class="text-danger" id="warningMessage"></div>

<div class="row">
    <div id="resultRow" class="col-md-3" style="max-height:50em;overflow-y:scroll;" >
        <input class="form-control" id="lessonSearchbar" type="search" />
    </div>
    <div class="col-md-9" style="padding-left: 0px; padding-right: 0px">
        <div class="ui-menu cnavbar" style="margin-left:4px;width:60em">
            <h3>Control center</h3>
            <div class="row" style="margin-left: 4px">
                <button id ="saveButton" class="btn btn-success">Save Changes</button>
                <button id="revertButton" class="btn btn-warning">Revert Changes</button>
                <button id="resetButton"class="btn btn-danger">Reset Graph</button>
            </div>
        </div>
        <div id="cy">
        
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.14.0/cytoscape.min.js")
@Scripts.Render("https://cdn.jsdelivr.net/npm/cytoscape-edgehandles@3.6.0/cytoscape-edgehandles.min.js")
@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js")
@Scripts.Render("~/Scripts/PageLogic/NodeGraph.js") 

Chearn/Chearn/Views/Cours/StudentCourses.cshtml
@model IEnumerable<Chearn.Models.Cours>

@{
    ViewBag.Title = "Student Courses";
}

<h2>Enrolled Courses</h2>


<div class="card-deck">
    @foreach (var course in Model)
    {
        <div class="card course" style="max-width:20em">
            <div class="card-body">
                <h5 class="card-title"><a href="@Url.Action("StudentCourse", "Cours", new { id = @course.ID })">@course.Name </a></h5>
                <hr />
            </div>
        </div>
    }
</div>